### ISSUE TITLE
Send button in compose box

### ISSUE THREAD

**Issue by satya164** [numixproject/org.numixproject.hermes#12]
![image](https://cloud.githubusercontent.com/assets/1174278/8637839/2ad1d72c-28c3-11e5-919a-8bac137e8ca5.png)

I would like to have a send button in the compose box itself when something is typed instead of the keyboard. Then it'll be easy to write multiline text as well.

**Comment by jamesweech** [comment]
This would be good although it might be best to have an option in settings for both, for example i often prefer typing then pressing enter to send especially when paired with my bluetooth keyboard

**Comment by PaoloRotolo** [comment]
Fixed in Hermes 1.2.4.
