### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by devmru** [numixproject/org.numixproject.hermes#13]
The problem with displaying Cyrillic
![Image](https://pbs.twimg.com/media/CKL1uRoUsAU8fTe.jpg)
Server: irc.turli.net
Sample text.
Taken from hexchat(PC on Linux).Also not correctly displayed.
```
-InfoServ- Äëÿ ïîäêëþ÷åíèÿ â ñåòü ÷åðåç tor, mibbit è irccloud íåîáõîäèìî àâòîðèçîâàòüñÿ ê âàøåìó àêêàóíòó íà ñåðâèñàõ ÷åðåç SASL. Â äàííîì ñëó÷àå èñïîëüçîâàíèå êèðèëëèöû â àêêàóíòå íå äîïóñòèìî!
-InfoServ- [Èíôîðìàöèÿ] Notice from i, posted 00:46:12 on 22/12/2014:
-InfoServ- Åñëè ó Âàñ âîçíèêëè âîïðîñû ïî IRC, îáðàòèòåñü íà êàíàë #help Öèòàòíèê Ðóíåòà - #bash Âèêòîðèíà íà êàíàëå #BuKToPuHa
```
Decrypt
```
-InfoServ- Для подключения в сеть через tor, mibbit и irccloud необходимо авторизоваться к вашему аккаунту на сервисах через SASL. В данном случае использование кириллицы в аккаунте не допустимо!
-InfoServ- [Информация] Notice from i, posted 00:46:12 on 22/12/2014:
-InfoServ- Если у Вас возникли вопросы по IRC, обратитесь на канал #help Цитатник Рунета - #bash Викторина на канале #BuKToPuHa
```
CP1252 → CP1251 
Decoded in [artlebedev tool](http://www.artlebedev.ru/tools/decoder/advanced/)

**Comment by PaoloRotolo** [comment]
Thanks. We'll try to fix it ASAP.

**Comment by PaoloRotolo** [comment]
Hi @devmru. We think this isn't really a bug.

Try to edit a Server and **change encoding preferences**. Maybe select *windows-1251*.

![screenshot from 2015-08-07 21-07-12](https://cloud.githubusercontent.com/assets/5623301/9143725/4fea67f6-3d48-11e5-959b-0ac7f36ca261.png)
![screenshot from 2015-08-07 21-06-15](https://cloud.githubusercontent.com/assets/5623301/9143726/4feaf6a8-3d48-11e5-8cea-6244b24ba128.png)
