### ISSUE TITLE
ZNC/Bouncer Support

### ISSUE THREAD

**Issue by numix-ood** [numixproject/org.numixproject.hermes#15]
Please add support for people who use bouncers such as ZNC. Usernames are not saved correctly and therefore you cannot log in. 

Debug info:
 OS Version: 3.4.0-Sultan-CAF(51a2daf920)
 OS API Level: 22
 Device: A0001
 Model (and Product): A0001 (bacon)
 RELEASE: 5.1.1
 BRAND: oneplus
 DISPLAY: bacon-userdebug 5.1.1 LMY48G 51a2daf920 test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: bacon
 Build ID: LMY48G
 MANUFACTURER: OnePlus
 SERIAL: 8ca9d8a9
 USER: sultan
 HOST: sultan-Satellite-S855-S5381

Extra Info: Hermes version: 1.2.5

**Comment by PaoloRotolo** [comment]
Fixed. Please look here: https://github.com/numixproject/org.numixproject.hermes/issues/9
