### ISSUE TITLE
Does not connect to server

### ISSUE THREAD

**Issue by atrnh** [numixproject/org.numixproject.hermes#18]
App doesn't connect to server, no matter how many times I pressed "connect".

I also paid to remove ads but they're still there

Debug info:
 OS Version: 3.4.0-gbebb36b(1863243)
 OS API Level: 22
 Device: hammerhead
 Model (and Product): Nexus 5 (hammerhead)
 RELEASE: 5.1.1
 BRAND: google
 DISPLAY: LMY48B
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: hammerhead
 Build ID: LMY48B
 MANUFACTURER: LGE
 SERIAL: 0325e66d09318370
 USER: android-build
 HOST: wpiu6.hot.corp.google.com

Extra Info: Hermes version: 1.2.6

**Comment by PaoloRotolo** [comment]
Hi @atrnh,
I've just released a new version (1.2.7) that shuold fix the issues.

Let me know if it works :)
