### ISSUE TITLE
Hermes design concept #1

### ISSUE THREAD

**Issue by PaoloRotolo** [numixproject/org.numixproject.hermes#2]
![img_20150209_193946](https://cloud.githubusercontent.com/assets/5623301/6155707/725fae3e-b235-11e4-9263-4eed12f05554.jpg)

![img_20150209_194020](https://cloud.githubusercontent.com/assets/5623301/6155708/72780614-b235-11e4-81c8-bcc9d7ad3822.jpg)

**Comment by PaoloRotolo** [comment]
![730110177_66929_17281828392866293333](https://cloud.githubusercontent.com/assets/5623301/6200888/2703df32-b48d-11e4-9983-c175fb6fb139.jpg)

![730111599_66306_12751993441824024666](https://cloud.githubusercontent.com/assets/5623301/6200889/27209ffa-b48d-11e4-90af-629d28f46a18.jpg)

**Comment by PaoloRotolo** [comment]
![730110956_66496_17371357742796055906](https://cloud.githubusercontent.com/assets/5623301/6200908/22b13a14-b48e-11e4-869d-6261d44a2821.jpg)

**Comment by satya164** [comment]
![screen - home](https://cloud.githubusercontent.com/assets/1174278/7046342/99c43774-de22-11e4-8323-92d7feb8c3ae.png)

![screen - server](https://cloud.githubusercontent.com/assets/1174278/7046345/a1176726-de22-11e4-96a3-73c53e41e8bf.png)

![screen - channel](https://cloud.githubusercontent.com/assets/1174278/7046349/a9e58162-de22-11e4-81d4-4b613ffa3c06.png)

**Comment by me4oslav** [comment]
In mockup 2 the three dots button host connect, disconnect, edit and delete options.
In mockup 3 the emoticon opens the system emoji pane. They work in IRC, we tested.

**Comment by satya164** [comment]
![screen - blank](https://cloud.githubusercontent.com/assets/1174278/7052708/dba142ce-de4d-11e4-83e5-7493658033c5.png)

![screen - home](https://cloud.githubusercontent.com/assets/1174278/7052711/dd8d078a-de4d-11e4-8bc2-002feeed9a31.png)

![screen - server](https://cloud.githubusercontent.com/assets/1174278/7052718/e3d6883c-de4d-11e4-8c02-717e72c17153.png)

![screen - channel](https://cloud.githubusercontent.com/assets/1174278/7052721/eb720b66-de4d-11e4-97d0-3cd7bbaaae9c.png)

![screen - add new server - server](https://cloud.githubusercontent.com/assets/1174278/7052729/f36f6750-de4d-11e4-8731-205f66637537.png)

![screen - add new server - user](https://cloud.githubusercontent.com/assets/1174278/7052731/f8d2a27a-de4d-11e4-91ab-85859c902bb4.png)

![screen - add new server - advanced](https://cloud.githubusercontent.com/assets/1174278/7052737/fe2cedca-de4d-11e4-9c99-8be0a62c6607.png)

**Comment by satya164** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="amaranth">#E91E63</color>
    <color name="sycamore">#4CAF50</color>
    <color name="bondi_blue">#0097A7</color>
    <color name="pomegranate_80pc">#CCF34236</color>
    <color name="dodger_blue_80pc">#CC2096F3</color>
</resources>
```
