### ISSUE TITLE
Cvb

### ISSUE THREAD

**Issue by numix-ood** [numixproject/org.numixproject.hermes#30]
ggh

Debug info:
 OS Version: 3.10.40-geec2459(2074855)
 OS API Level: 22
 Device: shamu
 Model (and Product): Nexus 6 (shamu)
 RELEASE: 5.1.1
 BRAND: google
 DISPLAY: LMY48I
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: shamu
 Build ID: LMY48I
 MANUFACTURER: motorola
 SERIAL: ZX1G22TXWQ
 USER: android-build
 HOST: wpds10.hot.corp.google.com

Extra Info: Hermes version: 1.2.7

**Comment by Foggalong** [comment]
@PaoloRotolo is there a way we can get a spam filter on this stuff?
