### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by niedzielski** [numixproject/org.numixproject.hermes#4]
I'm seeing a compilation error on `master` running `./gradlew assembleDebug`:

	org.numixproject.hermes/yaaic/src/main/java/org/numixproject/hermes/adapter/ServerListAdapter.java:215: error: no suitable constructor found for mentionsAdapter(ArrayList<String>,int)
	                roomsList.setAdapter(new mentionsAdapter(channels, Mentions));
	                                     ^
	    constructor mentionsAdapter.mentionsAdapter(String[],String[]) is not applicable
	      (actual argument ArrayList<String> cannot be converted to String[] by method invocation conversion)
	    constructor mentionsAdapter.mentionsAdapter() is not applicable
	      (actual and formal argument lists differ in length)

**Comment by PaoloRotolo** [comment]
Hi @niedzielski. I'm currently implementing the adapter, it's just not supposed to work right now :)
I'm going to commit a fix in a about one hour.

Regards,
Paolo

**Comment by niedzielski** [comment]
Sweet! I've been using the app, primarily read-only, for the past week and it's been great! Thanks!
