### ISSUE TITLE
You need a dark theme 

### ISSUE THREAD

**Issue by numix-ood** [numixproject/org.numixproject.hermes#42]
See title  

Debug info:
 OS Version: 3.4.42-g835800a(5)
 OS API Level: 22
 Device: victara
 Model (and Product): XT1095 (victara_tmo)
 RELEASE: 5.1
 BRAND: motorola
 DISPLAY: LPE23.32-21.3
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 Build ID: LPE23.32-21.3
 MANUFACTURER: motorola
 SERIAL: TA98907KWZ
 USER: hudsoncm
 HOST: ilclbld34

Extra Info: Hermes version: 1.2.7

**Comment by Foggalong** [comment]
Duplicate of #25
