### ISSUE TITLE
Server by default

### ISSUE THREAD

**Issue by loctauxphilippe** [numixproject/org.numixproject.hermes#5]
Maybe you can add freenode out of the box? It may be useful since I lot of people use it

**Comment by PaoloRotolo** [comment]
We added suggestions while user type a server. It should be easy now to add new servers, even if you don't know the exact address.

![screenshot_2015-05-21-21-09-17](https://cloud.githubusercontent.com/assets/5623301/7756773/b1865be2-fffd-11e4-99c9-8831ecd3b62c.png)
.

**Comment by loctauxphilippe** [comment]
\o/ aye! great!
