### ISSUE TITLE
Other text sizes

### ISSUE THREAD

**Issue by qaisjp** [numixproject/org.numixproject.hermes#7]
The ability to change text size between "normal", " small", and "smaller". IMO the text is pretty big atm.

**Comment by PaoloRotolo** [comment]
Fixed with commit **8a2a807**
![screenshot_2015-06-21-21-42-06](https://cloud.githubusercontent.com/assets/5623301/8273080/62c3b5a8-185e-11e5-92c8-ef48265c7dce.png)
. We'll release an update on Google Play tomorrow.
Thank you!

**Comment by qaisjp** [comment]
Thanks
