### ISSUE TITLE
Compact ActionBar

### ISSUE THREAD

**Issue by qaisjp** [numixproject/org.numixproject.hermes#8]
Androirc esque compact actionbar

**Comment by me4oslav** [comment]
Elaborate

**Comment by qaisjp** [comment]
An elaborate feature indeed... in all seriousness, compact mode just has a thinner ActionBar. A thinner message input box would suit Hermes as well

**Comment by PaoloRotolo** [comment]
I think @me4oslav just wanted you to better elaborate what a Compat ActionBar is :)
