### ISSUE TITLE
ZNC connection issue

### ISSUE THREAD

**Issue by voodooboy3000** [numixproject/org.numixproject.hermes#9]
I am having some trouble connecting to my ZNC server.  My connection works fine in Rice IRC but using the same settings in Hermes I get immediate disconnects. Let me know what other information you need.

**Comment by smehernosh** [comment]
I'm having the same issue. I'm able to connect using Holo IRC.

**Comment by zkanda** [comment]
Same here. Always incorrect password.

**Comment by jamesweech** [comment]
+1 Please fix this and I'll pay for ad removal

**Comment by PaoloRotolo** [comment]
Hi guys. I've just fixed that in our internal build.
We'll release an update on Google Play soon. Thank you!

**Comment by voodooboy3000** [comment]
Thanks I am in China at the moment so I will test once I can get google play
